name: C unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test all libraries
      run: |
        cmake . -DCMAKE_BUILD_TYPE=Debug
        make
        ctest --output-on-failure
